<a href="https://colab.research.google.com/github/Alanraj18/SIRPI-/blob/main/Nagarajan_C_Test_Section_C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = {'Customer_ID': [101, 102, 103, 104, 105],
'Purchase_Amount': [500, 1200, 300, 800, 1500],
'Purchase_Date': ['2024-01-10', '2024-02-15', '2024-01-25', '2024-03-05', '2024-02-20']}
df = pd.DataFrame(data)

In [ ]:
# Convert Purchase_Date to a proper datetime format.
df['Purchase_Date'] = pd.to_datetime(df['Purchase_Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      5 non-null      int64
 1   Purchase_Amount  5 non-null      int64
 2   Purchase_Date    5 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(2)
memory usage: 252.0 bytes

In [ ]:
# Extract and add a new column for the month of purchase.
df['Purchase_Month'] = df['Purchase_Date'].dt.month
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      5 non-null      int64
 1   Purchase_Amount  5 non-null      int64
 2   Purchase_Date    5 non-null      datetime64[ns]
 3   Purchase_Month   5 non-null      int32
dtypes: datetime64[ns](1), int32(1), int64(2)
memory usage: 272.0 bytes

In [ ]:
# Create a new column indicating whether a purchase is High Value (Purchase_Amount > 1000) or Low Value.
df["Purchase_rate"] = df["Purchase_Amount"] > 1000
df["Purchase_rate"] = df["Purchase_rate"].replace({True:"High Value",False:"Low Value"})
df.head()

   Customer_ID  Purchase_Amount Purchase_Date  Purchase_Month Purchase_rate
0          101              500    2024-01-10               1     Low Value
1          102             1200    2024-02-15               2    High Value
2          103              300    2024-01-25               1     Low Value
3          104              800    2024-03-05               3     Low Value
4          105             1500    2024-02-20               2    High Value

In [ ]:
# Group the data by month and calculate the total revenue per month.
df.groupby("Purchase_Month")["Purchase_Amount"].sum()

Purchase_Month
1     800
2    2700
3     800
Name: Purchase_Amount, dtype: int64

In [ ]:
# Sort the customers by Purchase Amount in descending order and display the top 3 customers.
df.sort_values(by="Purchase_Amount",ascending=False).head(3)

   Customer_ID  Purchase_Amount Purchase_Date  Purchase_Month Purchase_rate
4          105             1500    2024-02-20               2    High Value
1          102             1200    2024-02-15               2    High Value
3          104              800    2024-03-05               3     Low Value

In [15]:
data={'House_ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      'Size_sqft': [1500, 1800, None, 2200, 3000, 4000, 5000, None, 6000, 7000],
      'Num_Bedrooms': [3, 4, 3, 5, 4, 6, 7, 3, 5, 6],
      'Price': [300000, 400000, 350000, 500000, 600000, 750000, 900000, 450000, 1100000, 1200000]}
df=pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   House_ID      10 non-null     int64
 1   Size_sqft     8 non-null      float64
 2   Num_Bedrooms  10 non-null     int64
 3   Price         10 non-null     int64
dtypes: float64(1), int64(3)
memory usage: 452.0 bytes

In [ ]:
#  Identify missing values in the dataset. • Fill missing values in the Size_sqft column using the median of the available values.
df.isnull().sum()

House_ID        0
Size_sqft       2
Num_Bedrooms    0
Price           0
dtype: int64

In [18]:
df["Size_sqft"] = df["Size_sqft"].fillna(df["Size_sqft"].median())
df.isnull().sum()

House_ID        0
Size_sqft       0
Num_Bedrooms    0
Price           0
dtype: int64

In [ ]:
# Detect & Handle Outliers: • Use the Interquartile Range (IQR) method to detect and remove outliers in Size_sqft and Price. • Print how many outliers were removed.
Q1 = df[['Size_sqft', 'Price']].quantile(0.25)
Q3 = df[['Size_sqft', 'Price']].quantile(0.75)
IQR=Q3-Q1
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR
outliers=(df[['Size_sqft', 'Price']] < lower_bound) | (df[['Size_sqft', 'Price']] > upper_bound)
outliers_count=outliers.sum()
print("Outliers count:\n",outliers_count)

Outliers count:
 Size_sqft    0
Price        0
dtype: int64